import { rm, mkdir, writeFile } from "node:fs/promises";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";
import { z, type ZodType } from "zod";

import { ArtifactSchema } from "../../packages/core/src/domain/schemas/artifact";
import { ErrorRecordSchema } from "../../packages/core/src/domain/schemas/error";
import { IdempotencyRecordSchema } from "../../packages/core/src/domain/schemas/idempotency";
import { LockRecordSchema } from "../../packages/core/src/domain/schemas/lock";
import { TaskCardSchema } from "../../packages/core/src/domain/schemas/task";

type JsonSchema = {
  $schema?: string;
  $id?: string;
  title?: string;
  type?: string | string[];
  enum?: unknown[];
  properties?: Record<string, JsonSchema>;
  required?: string[];
  additionalProperties?: boolean;
  items?: JsonSchema;
  anyOf?: JsonSchema[];
  oneOf?: JsonSchema[];
  allOf?: JsonSchema[];
  minLength?: number;
  maxLength?: number;
  minimum?: number;
  maximum?: number;
  format?: string;
};

type SchemaDefinition = {
  name: string;
  slug: string;
  sourcePath: string;
  exportName: string;
  schema: ZodType;
};

type FieldRow = {
  field: string;
  required: string;
  nullable: string;
  type: string;
  constraints: string;
};

const repoRoot = join(dirname(fileURLToPath(import.meta.url)), "../..");
const markdownDir = join(repoRoot, "docs/generated/schema");
const jsonSchemaDir = join(repoRoot, "docs/generated/json-schema");

const schemaDefinitions: SchemaDefinition[] = [
  {
    name: "TaskCard",
    slug: "task-card",
    sourcePath: "packages/core/src/domain/schemas/task.ts",
    exportName: "TaskCardSchema",
    schema: TaskCardSchema
  },
  {
    name: "Artifact",
    slug: "artifact",
    sourcePath: "packages/core/src/domain/schemas/artifact.ts",
    exportName: "ArtifactSchema",
    schema: ArtifactSchema
  },
  {
    name: "ErrorRecord",
    slug: "error-record",
    sourcePath: "packages/core/src/domain/schemas/error.ts",
    exportName: "ErrorRecordSchema",
    schema: ErrorRecordSchema
  },
  {
    name: "IdempotencyRecord",
    slug: "idempotency-record",
    sourcePath: "packages/core/src/domain/schemas/idempotency.ts",
    exportName: "IdempotencyRecordSchema",
    schema: IdempotencyRecordSchema
  },
  {
    name: "LockRecord",
    slug: "lock-record",
    sourcePath: "packages/core/src/domain/schemas/lock.ts",
    exportName: "LockRecordSchema",
    schema: LockRecordSchema
  }
];

async function main(): Promise<void> {
  await recreateDirectory(markdownDir);
  await recreateDirectory(jsonSchemaDir);

  for (const definition of schemaDefinitions) {
    const jsonSchema = buildJsonSchema(definition);
    const markdown = buildMarkdown(definition, jsonSchema);

    await writeFile(
      join(jsonSchemaDir, `${definition.slug}.json`),
      `${JSON.stringify(jsonSchema, null, 2)}\n`,
      "utf8"
    );
    await writeFile(join(markdownDir, `${definition.slug}.md`), markdown, "utf8");
  }
}

async function recreateDirectory(path: string): Promise<void> {
  await rm(path, { recursive: true, force: true });
  await mkdir(path, { recursive: true });
}

function buildJsonSchema(definition: SchemaDefinition): JsonSchema {
  const generated = z.toJSONSchema(definition.schema) as JsonSchema;
  const { $schema, ...schemaBody } = generated;

  return {
    $schema: $schema ?? "https://json-schema.org/draft/2020-12/schema",
    $id: `https://shud-harness.local/generated/json-schema/${definition.slug}.json`,
    title: definition.name,
    ...schemaBody
  };
}

function buildMarkdown(definition: SchemaDefinition, jsonSchema: JsonSchema): string {
  const fields = flattenFields(jsonSchema);
  const enumFields = fields.filter((field) => field.constraints.startsWith("values: "));

  const lines = [
    "<!-- Generated by scripts/schema/generate.ts. Do not edit manually. -->",
    "",
    `# ${definition.name} Schema`,
    "",
    `Source: \`${definition.sourcePath}\` (\`${definition.exportName}\`)`,
    "",
    "Required is evaluated within the immediate parent object.",
    "",
    "## Fields",
    "",
    "| Field | Required | Nullable | Type | Constraints / values |",
    "|---|---|---|---|---|",
    ...fields.map(
      (field) =>
        `| ${cell(field.field)} | ${cell(field.required)} | ${cell(field.nullable)} | ${cell(
          field.type
        )} | ${cell(field.constraints)} |`
    )
  ];

  if (enumFields.length > 0) {
    lines.push(
      "",
      "## Enums",
      "",
      "| Field | Values |",
      "|---|---|",
      ...enumFields.map((field) => `| ${cell(field.field)} | ${cell(stripValuesPrefix(field.constraints))} |`)
    );
  }

  return `${lines.join("\n")}\n`;
}

function flattenFields(schema: JsonSchema, parentPath = ""): FieldRow[] {
  const objectSchema = nonNullSchema(schema);

  if (objectSchema.type !== "object" || objectSchema.properties === undefined) {
    throw new Error(`Expected object schema at ${parentPath || "<root>"}`);
  }

  const required = new Set(objectSchema.required ?? []);
  const rows: FieldRow[] = [];

  for (const [propertyName, propertySchema] of Object.entries(objectSchema.properties)) {
    const fieldPath = parentPath === "" ? propertyName : `${parentPath}.${propertyName}`;
    const propertyWithoutNull = nonNullSchema(propertySchema);

    rows.push({
      field: fieldPath,
      required: required.has(propertyName) ? "yes" : "no",
      nullable: isNullable(propertySchema) ? "yes" : "no",
      type: typeLabel(propertySchema),
      constraints: constraintLabel(propertySchema)
    });

    if (propertyWithoutNull.type === "object" && propertyWithoutNull.properties !== undefined) {
      rows.push(...flattenFields(propertyWithoutNull, fieldPath));
    }
  }

  return rows;
}

function nonNullSchema(schema: JsonSchema): JsonSchema {
  if (Array.isArray(schema.type)) {
    const nonNullTypes = schema.type.filter((type) => type !== "null");
    return { ...schema, type: nonNullTypes.length === 1 ? nonNullTypes[0] : nonNullTypes };
  }

  const union = schema.anyOf ?? schema.oneOf;
  const nonNullMembers = union?.filter((member) => member.type !== "null");
  if (nonNullMembers !== undefined && nonNullMembers.length === 1) {
    return nonNullMembers[0];
  }

  return schema;
}

function isNullable(schema: JsonSchema): boolean {
  if (Array.isArray(schema.type)) {
    return schema.type.includes("null");
  }

  const union = schema.anyOf ?? schema.oneOf;
  return union?.some((member) => member.type === "null") ?? false;
}

function typeLabel(schema: JsonSchema): string {
  const nullable = isNullable(schema);
  const schemaWithoutNull = nonNullSchema(schema);
  const label = typeLabelNonNull(schemaWithoutNull);

  return nullable ? `${label} | null` : label;
}

function typeLabelNonNull(schema: JsonSchema): string {
  if (schema.enum !== undefined) {
    return "enum<string>";
  }

  if (schema.type === "array") {
    return `array<${schema.items === undefined ? "unknown" : typeLabel(schema.items)}>`;
  }

  if (Array.isArray(schema.type)) {
    return schema.type.join(" | ");
  }

  if (schema.anyOf !== undefined) {
    return `anyOf<${schema.anyOf.map(typeLabel).join(" | ")}>`;
  }

  if (schema.oneOf !== undefined) {
    return `oneOf<${schema.oneOf.map(typeLabel).join(" | ")}>`;
  }

  if (schema.allOf !== undefined) {
    return `allOf<${schema.allOf.map(typeLabel).join(" & ")}>`;
  }

  return schema.type ?? "unknown";
}

function constraintLabel(schema: JsonSchema): string {
  const schemaWithoutNull = nonNullSchema(schema);
  const constraints: string[] = [];

  if (schemaWithoutNull.enum !== undefined) {
    constraints.push(`values: ${schemaWithoutNull.enum.map((value) => `\`${String(value)}\``).join(", ")}`);
  }

  if (schemaWithoutNull.minLength !== undefined) {
    constraints.push(`minLength=${schemaWithoutNull.minLength}`);
  }

  if (schemaWithoutNull.maxLength !== undefined) {
    constraints.push(`maxLength=${schemaWithoutNull.maxLength}`);
  }

  if (schemaWithoutNull.minimum !== undefined) {
    constraints.push(`minimum=${schemaWithoutNull.minimum}`);
  }

  if (schemaWithoutNull.maximum !== undefined) {
    constraints.push(`maximum=${schemaWithoutNull.maximum}`);
  }

  if (schemaWithoutNull.format !== undefined) {
    constraints.push(`format=${schemaWithoutNull.format}`);
  }

  if (schemaWithoutNull.type === "array" && schemaWithoutNull.items !== undefined) {
    const itemConstraints = constraintLabel(schemaWithoutNull.items);
    if (itemConstraints !== "-") {
      constraints.push(`items: ${itemConstraints}`);
    }
  }

  if (schemaWithoutNull.type === "object" && schemaWithoutNull.additionalProperties === false) {
    constraints.push("additionalProperties=false");
  }

  return constraints.length === 0 ? "-" : constraints.join("; ");
}

function stripValuesPrefix(value: string): string {
  return value.replace(/^values: /, "");
}

function cell(value: string): string {
  return value.replace(/\|/g, "\\|");
}

main().catch((error: unknown) => {
  console.error(error instanceof Error ? error.message : String(error));
  process.exitCode = 1;
});
