import { createHash } from "node:crypto";
import { rm, mkdir, readFile, readdir, writeFile } from "node:fs/promises";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";
import { z, type ZodType } from "zod";

import { ArtifactSchema } from "../../packages/core/src/domain/schemas/artifact";
import { ErrorRecordSchema } from "../../packages/core/src/domain/schemas/error";
import { IdempotencyRecordSchema } from "../../packages/core/src/domain/schemas/idempotency";
import { LockRecordSchema } from "../../packages/core/src/domain/schemas/lock";
import { TaskCardSchema } from "../../packages/core/src/domain/schemas/task";

type JsonSchema = {
  $schema?: string;
  $id?: string;
  title?: string;
  type?: string | string[];
  enum?: unknown[];
  properties?: Record<string, JsonSchema>;
  required?: string[];
  additionalProperties?: boolean;
  items?: JsonSchema;
  anyOf?: JsonSchema[];
  oneOf?: JsonSchema[];
  allOf?: JsonSchema[];
  minLength?: number;
  maxLength?: number;
  minimum?: number;
  maximum?: number;
  format?: string;
};

type SchemaDefinition = {
  name: string;
  slug: string;
  sourcePath: string;
  exportName: string;
  schema: ZodType;
};

type FieldRow = {
  field: string;
  required: string;
  nullable: string;
  type: string;
  constraints: string;
};

type ObjectSchemaExport = {
  exportName: string;
  sourcePath: string;
};

const repoRoot = join(dirname(fileURLToPath(import.meta.url)), "../..");
const schemaSourceDir = join(repoRoot, "packages/core/src/domain/schemas");
const markdownDir = join(repoRoot, "docs/generated/schema");
const jsonSchemaDir = join(repoRoot, "docs/generated/json-schema");

const schemaDefinitions: SchemaDefinition[] = [
  {
    name: "TaskCard",
    slug: "task-card",
    sourcePath: "packages/core/src/domain/schemas/task.ts",
    exportName: "TaskCardSchema",
    schema: TaskCardSchema
  },
  {
    name: "Artifact",
    slug: "artifact",
    sourcePath: "packages/core/src/domain/schemas/artifact.ts",
    exportName: "ArtifactSchema",
    schema: ArtifactSchema
  },
  {
    name: "ErrorRecord",
    slug: "error-record",
    sourcePath: "packages/core/src/domain/schemas/error.ts",
    exportName: "ErrorRecordSchema",
    schema: ErrorRecordSchema
  },
  {
    name: "IdempotencyRecord",
    slug: "idempotency-record",
    sourcePath: "packages/core/src/domain/schemas/idempotency.ts",
    exportName: "IdempotencyRecordSchema",
    schema: IdempotencyRecordSchema
  },
  {
    name: "LockRecord",
    slug: "lock-record",
    sourcePath: "packages/core/src/domain/schemas/lock.ts",
    exportName: "LockRecordSchema",
    schema: LockRecordSchema
  }
];

const nestedObjectSchemaExports = new Set(["ErrorRemediationSchema", "InferenceBudgetSchema"]);

async function main(): Promise<void> {
  if (process.argv.includes("--self-test")) {
    runSelfTest();
    return;
  }

  await assertSchemaRegistryComplete();
  await recreateDirectory(markdownDir);
  await recreateDirectory(jsonSchemaDir);

  for (const definition of schemaDefinitions) {
    const jsonSchema = buildJsonSchema(definition);
    const markdown = buildMarkdown(definition, jsonSchema);

    await writeFile(
      join(jsonSchemaDir, `${definition.slug}.json`),
      `${JSON.stringify(jsonSchema, null, 2)}\n`,
      "utf8"
    );
    await writeFile(join(markdownDir, `${definition.slug}.md`), markdown, "utf8");
  }
}

async function recreateDirectory(path: string): Promise<void> {
  await rm(path, { recursive: true, force: true });
  await mkdir(path, { recursive: true });
}

function buildJsonSchema(definition: SchemaDefinition): JsonSchema {
  const generated = z.toJSONSchema(definition.schema, { io: "input" }) as JsonSchema;
  const { $schema, ...schemaBody } = generated;

  return {
    $schema: $schema ?? "https://json-schema.org/draft/2020-12/schema",
    $id: `https://shud-harness.local/generated/json-schema/${definition.slug}.json`,
    title: definition.name,
    ...schemaBody
  };
}

function buildMarkdown(definition: SchemaDefinition, jsonSchema: JsonSchema): string {
  const fields = flattenFields(jsonSchema);
  const enumFields = fields.filter((field) => field.constraints.startsWith("values: "));
  const example = buildExample(jsonSchema);
  const changelogLines = buildChangelogDiff(definition, jsonSchema, fields);

  const lines = [
    "<!-- Generated by scripts/schema/generate.ts. Do not edit manually. -->",
    "",
    `# ${definition.name} Schema`,
    "",
    `Source: \`${definition.sourcePath}\` (\`${definition.exportName}\`)`,
    "",
    "Required is evaluated within the immediate parent object.",
    "",
    "## Fields",
    "",
    "| Field | Required | Nullable | Type | Constraints / values |",
    "|---|---|---|---|---|",
    ...fields.map(
      (field) =>
        `| ${cell(field.field)} | ${cell(field.required)} | ${cell(field.nullable)} | ${cell(
          field.type
        )} | ${cell(field.constraints)} |`
    )
  ];

  if (enumFields.length > 0) {
    lines.push(
      "",
      "## Enums",
      "",
      "| Field | Values |",
      "|---|---|",
      ...enumFields.map((field) => `| ${cell(field.field)} | ${cell(stripValuesPrefix(field.constraints))} |`)
    );
  }

  lines.push(
    "",
    "## Example YAML",
    "",
    "```yaml",
    ...yamlLines(example),
    "```",
    "",
    "## Changelog Diff",
    "",
    "```diff",
    ...changelogLines,
    "```"
  );

  return `${lines.join("\n")}\n`;
}

async function assertSchemaRegistryComplete(): Promise<void> {
  const sourceExports = await discoverObjectSchemaExports();
  validateSchemaRegistryCoverage(sourceExports, schemaDefinitions, nestedObjectSchemaExports);
}

async function discoverObjectSchemaExports(): Promise<ObjectSchemaExport[]> {
  const files = (await readdir(schemaSourceDir))
    .filter((file) => file.endsWith(".ts") && file !== "index.ts" && !file.endsWith(".test.ts"))
    .sort();
  const exports: ObjectSchemaExport[] = [];

  for (const file of files) {
    const sourcePath = `packages/core/src/domain/schemas/${file}`;
    const source = await readFile(join(schemaSourceDir, file), "utf8");
    const exportRegex = /export\s+const\s+([A-Za-z0-9_]+Schema)\s*=\s*z\.object\s*\(/g;
    for (const match of source.matchAll(exportRegex)) {
      exports.push({ exportName: match[1], sourcePath });
    }
  }

  return exports.sort((left, right) => left.exportName.localeCompare(right.exportName));
}

function validateSchemaRegistryCoverage(
  sourceExports: ObjectSchemaExport[],
  definitions: SchemaDefinition[],
  ignoredNestedExports: Set<string>
): void {
  const sourceByName = new Map(sourceExports.map((sourceExport) => [sourceExport.exportName, sourceExport]));
  const generatedNames = new Set(definitions.map((definition) => definition.exportName));
  const missing = sourceExports.filter(
    (sourceExport) => !ignoredNestedExports.has(sourceExport.exportName) && !generatedNames.has(sourceExport.exportName)
  );
  const stale = definitions.filter((definition) => !sourceByName.has(definition.exportName));

  if (missing.length > 0 || stale.length > 0) {
    const details = [
      ...missing.map(
        (sourceExport) =>
          `missing generated schema registry entry for ${sourceExport.exportName} from ${sourceExport.sourcePath}`
      ),
      ...stale.map((definition) => `stale generated schema registry entry ${definition.exportName}`)
    ];
    throw new Error(`Schema registry coverage failed:\n${details.join("\n")}`);
  }
}

function flattenFields(schema: JsonSchema, parentPath = ""): FieldRow[] {
  const objectSchema = nonNullSchema(schema);

  if (objectSchema.type !== "object" || objectSchema.properties === undefined) {
    throw new Error(`Expected object schema at ${parentPath || "<root>"}`);
  }

  const required = new Set(objectSchema.required ?? []);
  const rows: FieldRow[] = [];

  for (const [propertyName, propertySchema] of Object.entries(objectSchema.properties)) {
    const fieldPath = parentPath === "" ? propertyName : `${parentPath}.${propertyName}`;
    const propertyWithoutNull = nonNullSchema(propertySchema);

    rows.push({
      field: fieldPath,
      required: required.has(propertyName) ? "yes" : "no",
      nullable: isNullable(propertySchema) ? "yes" : "no",
      type: typeLabel(propertySchema),
      constraints: constraintLabel(propertySchema)
    });

    if (propertyWithoutNull.type === "object" && propertyWithoutNull.properties !== undefined) {
      rows.push(...flattenFields(propertyWithoutNull, fieldPath));
    }
  }

  return rows;
}

function nonNullSchema(schema: JsonSchema): JsonSchema {
  if (Array.isArray(schema.type)) {
    const nonNullTypes = schema.type.filter((type) => type !== "null");
    return { ...schema, type: nonNullTypes.length === 1 ? nonNullTypes[0] : nonNullTypes };
  }

  const union = schema.anyOf ?? schema.oneOf;
  const nonNullMembers = union?.filter((member) => member.type !== "null");
  if (nonNullMembers !== undefined && nonNullMembers.length === 1) {
    return nonNullMembers[0];
  }

  return schema;
}

function isNullable(schema: JsonSchema): boolean {
  if (Array.isArray(schema.type)) {
    return schema.type.includes("null");
  }

  const union = schema.anyOf ?? schema.oneOf;
  return union?.some((member) => member.type === "null") ?? false;
}

function typeLabel(schema: JsonSchema): string {
  const nullable = isNullable(schema);
  const schemaWithoutNull = nonNullSchema(schema);
  const label = typeLabelNonNull(schemaWithoutNull);

  return nullable ? `${label} | null` : label;
}

function typeLabelNonNull(schema: JsonSchema): string {
  if (schema.enum !== undefined) {
    return "enum<string>";
  }

  if (schema.type === "array") {
    return `array<${schema.items === undefined ? "unknown" : typeLabel(schema.items)}>`;
  }

  if (Array.isArray(schema.type)) {
    return schema.type.join(" | ");
  }

  if (schema.anyOf !== undefined) {
    return `anyOf<${schema.anyOf.map(typeLabel).join(" | ")}>`;
  }

  if (schema.oneOf !== undefined) {
    return `oneOf<${schema.oneOf.map(typeLabel).join(" | ")}>`;
  }

  if (schema.allOf !== undefined) {
    return `allOf<${schema.allOf.map(typeLabel).join(" & ")}>`;
  }

  return schema.type ?? "unknown";
}

function constraintLabel(schema: JsonSchema): string {
  const schemaWithoutNull = nonNullSchema(schema);
  const constraints: string[] = [];

  if (schemaWithoutNull.enum !== undefined) {
    constraints.push(`values: ${schemaWithoutNull.enum.map((value) => `\`${String(value)}\``).join(", ")}`);
  }

  if (schemaWithoutNull.minLength !== undefined) {
    constraints.push(`minLength=${schemaWithoutNull.minLength}`);
  }

  if (schemaWithoutNull.maxLength !== undefined) {
    constraints.push(`maxLength=${schemaWithoutNull.maxLength}`);
  }

  if (schemaWithoutNull.minimum !== undefined) {
    constraints.push(`minimum=${schemaWithoutNull.minimum}`);
  }

  if (schemaWithoutNull.maximum !== undefined) {
    constraints.push(`maximum=${schemaWithoutNull.maximum}`);
  }

  if (schemaWithoutNull.format !== undefined) {
    constraints.push(`format=${schemaWithoutNull.format}`);
  }

  if (schemaWithoutNull.type === "array" && schemaWithoutNull.items !== undefined) {
    const itemConstraints = constraintLabel(schemaWithoutNull.items);
    if (itemConstraints !== "-") {
      constraints.push(`items: ${itemConstraints}`);
    }
  }

  if (schemaWithoutNull.type === "object" && schemaWithoutNull.additionalProperties === false) {
    constraints.push("additionalProperties=false");
  }

  return constraints.length === 0 ? "-" : constraints.join("; ");
}

function buildExample(schema: JsonSchema): unknown {
  const schemaWithoutNull = nonNullSchema(schema);

  if (schemaWithoutNull.enum !== undefined) {
    return schemaWithoutNull.enum[0];
  }

  if (schemaWithoutNull.type === "object") {
    const example: Record<string, unknown> = {};
    for (const [propertyName, propertySchema] of Object.entries(schemaWithoutNull.properties ?? {})) {
      example[propertyName] = buildExample(propertySchema);
    }
    return example;
  }

  if (schemaWithoutNull.type === "array") {
    return [schemaWithoutNull.items === undefined ? "example" : buildExample(schemaWithoutNull.items)];
  }

  if (schemaWithoutNull.type === "integer" || schemaWithoutNull.type === "number") {
    return schemaWithoutNull.minimum ?? 0;
  }

  if (schemaWithoutNull.type === "boolean") {
    return false;
  }

  if (schemaWithoutNull.type === "null") {
    return null;
  }

  return "example";
}

function yamlLines(value: unknown, indent = 0): string[] {
  const prefix = " ".repeat(indent);

  if (Array.isArray(value)) {
    return value.flatMap((item) => {
      if (isPlainObject(item)) {
        return [`${prefix}-`, ...yamlLines(item, indent + 2)];
      }
      return [`${prefix}- ${yamlScalar(item)}`];
    });
  }

  if (isPlainObject(value)) {
    return Object.entries(value).flatMap(([key, item]) => {
      if (isPlainObject(item) || Array.isArray(item)) {
        return [`${prefix}${key}:`, ...yamlLines(item, indent + 2)];
      }
      return [`${prefix}${key}: ${yamlScalar(item)}`];
    });
  }

  return [`${prefix}${yamlScalar(value)}`];
}

function yamlScalar(value: unknown): string {
  if (value === null) {
    return "null";
  }
  if (typeof value === "number" || typeof value === "boolean") {
    return String(value);
  }
  return JSON.stringify(String(value));
}

function isPlainObject(value: unknown): value is Record<string, unknown> {
  return typeof value === "object" && value !== null && !Array.isArray(value);
}

function buildChangelogDiff(definition: SchemaDefinition, jsonSchema: JsonSchema, fields: FieldRow[]): string[] {
  const fingerprint = createHash("sha256").update(JSON.stringify(jsonSchema)).digest("hex");
  return [
    `+ schema ${definition.name} sha256:${fingerprint}`,
    ...fields.map(
      (field) =>
        `+ field ${field.field} required=${field.required} nullable=${field.nullable} type=${field.type} constraints=${field.constraints}`
    )
  ];
}

function runSelfTest(): void {
  const mockSchema = z.object({});
  const mockDefinitions: SchemaDefinition[] = [
    {
      name: "TaskCard",
      slug: "task-card",
      sourcePath: "packages/core/src/domain/schemas/task.ts",
      exportName: "TaskCardSchema",
      schema: mockSchema
    }
  ];
  const ignored = new Set(["InferenceBudgetSchema"]);

  validateSchemaRegistryCoverage(
    [
      { exportName: "TaskCardSchema", sourcePath: "packages/core/src/domain/schemas/task.ts" },
      { exportName: "InferenceBudgetSchema", sourcePath: "packages/core/src/domain/schemas/task.ts" }
    ],
    mockDefinitions,
    ignored
  );

  assertThrows(
    () =>
      validateSchemaRegistryCoverage(
        [
          { exportName: "TaskCardSchema", sourcePath: "packages/core/src/domain/schemas/task.ts" },
          { exportName: "RunJobSchema", sourcePath: "packages/core/src/domain/schemas/run-job.ts" }
        ],
        mockDefinitions,
        ignored
      ),
    "missing generated schema registry entry for RunJobSchema"
  );

  assertThrows(
    () =>
      validateSchemaRegistryCoverage([], mockDefinitions, ignored),
    "stale generated schema registry entry TaskCardSchema"
  );

  assertTaskCardUnknownKeyParity();
  for (const definition of schemaDefinitions) {
    assertNoAdditionalPropertiesFalse(buildJsonSchema(definition), definition.name);
  }

  console.log("schema generator self-test passed");
}

function assertTaskCardUnknownKeyParity(): void {
  const candidate = {
    task_id: "TASK-0001",
    type: "engineering",
    status: "created",
    runtime_phase: null,
    title: "Schema parity fixture",
    question_or_goal: "Prove generated JSON Schema does not reject Zod-accepted unknown keys.",
    created_by: "codex",
    current_owner: "codex",
    reviewer: "reviewer",
    inference_budget: {
      mode: "normal",
      advisory_usd: 1,
      advisory_model_calls: 1,
      reviewer_enabled: false,
      nested_trace: "accepted then stripped"
    },
    linked_jobs: [],
    linked_reports: [],
    created_at: "2026-07-06T00:00:00Z",
    updated_at: "2026-07-06T00:00:00Z",
    client_trace_id: "accepted then stripped"
  };
  const parsed = TaskCardSchema.safeParse(candidate);

  if (!parsed.success) {
    throw new Error("TaskCard unknown-key parity fixture should parse successfully");
  }

  if ("client_trace_id" in (parsed.data as Record<string, unknown>)) {
    throw new Error("TaskCardSchema should strip unknown root keys");
  }

  if ("nested_trace" in (parsed.data.inference_budget as Record<string, unknown>)) {
    throw new Error("TaskCardSchema should strip unknown nested object keys");
  }
}

function assertNoAdditionalPropertiesFalse(schema: JsonSchema, path: string): void {
  const schemaWithoutNull = nonNullSchema(schema);

  if (schemaWithoutNull.additionalProperties === false) {
    throw new Error(`${path} JSON Schema is stricter than Zod input semantics`);
  }

  if (schemaWithoutNull.type === "object") {
    for (const [propertyName, propertySchema] of Object.entries(schemaWithoutNull.properties ?? {})) {
      assertNoAdditionalPropertiesFalse(propertySchema, `${path}.${propertyName}`);
    }
  }

  if (schemaWithoutNull.type === "array" && schemaWithoutNull.items !== undefined) {
    assertNoAdditionalPropertiesFalse(schemaWithoutNull.items, `${path}[]`);
  }

  for (const [label, members] of [
    ["anyOf", schemaWithoutNull.anyOf],
    ["oneOf", schemaWithoutNull.oneOf],
    ["allOf", schemaWithoutNull.allOf]
  ] as const) {
    members?.forEach((member, index) => {
      assertNoAdditionalPropertiesFalse(member, `${path}.${label}[${index}]`);
    });
  }
}

function assertThrows(callback: () => void, expectedMessage: string): void {
  try {
    callback();
  } catch (error) {
    const message = error instanceof Error ? error.message : String(error);
    if (message.includes(expectedMessage)) {
      return;
    }
    throw new Error(`Expected error containing ${expectedMessage}, got ${message}`);
  }
  throw new Error(`Expected error containing ${expectedMessage}`);
}

function stripValuesPrefix(value: string): string {
  return value.replace(/^values: /, "");
}

function cell(value: string): string {
  return value.replace(/\|/g, "\\|");
}

main().catch((error: unknown) => {
  console.error(error instanceof Error ? error.message : String(error));
  process.exitCode = 1;
});
